player_portal/player_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("portal_web.urls")),
]

player_portal/portal_web/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (IndexView,
                    CustomLoginView,
                    SignUpView,
                    WGPlayerSearchView,
                    CreateProfileView,
                    DetailedStatView,
                    ProfileView,
                    SubscriptionView,
                    BoostView,
                    TankStatsView,
                    )

app_name = 'portal_web'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('wg_player_search', WGPlayerSearchView.as_view(), name='wg_player_search'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('detailed_stats/', DetailedStatView.as_view(), name='detailed_stats'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    path('boost/', BoostView.as_view(), name='boost'),
    path('tank_stats/<int:pk>/', TankStatsView.as_view(), name='tank_stats'),
]

player_portal/portal_web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator


class PlayerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    nickname = models.CharField(max_length=120)
    player_id = models.IntegerField()
    battles = models.PositiveIntegerField(null=True, blank=True)
    current_wn8 = models.FloatField(null=True, blank=True)
    desired_wn8 = models.PositiveIntegerField(null=True, validators=[MaxValueValidator(9999)])
    premium_expires = models.DateTimeField(null=True, blank=True)

    class Meta:
        permissions = [
            ("premium_account", "User has access to premium features"),
        ]

player_portal/portal_web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    """Form for user registration"""
    username = forms.CharField(widget=forms.TextInput(attrs={
        'name': 'username',
        'class': 'form-control',
        'placeholder': 'Username',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'name': 'password',
        'class': 'form-control',
        'placeholder': 'Create password',
        'type': 'password',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'name': 'password',
        'class': 'form-control',
        'placeholder': 'Confirm password',
        'type': 'password',
    }))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    """Form for login"""
    username = forms.CharField(widget=forms.TextInput(attrs={
        'name': 'username',
        'class': 'form-control',
        'placeholder': 'Username',
        "autofocus": True
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'name': 'password',
        'class': 'form-control',
        'placeholder': 'Password',
    }))

player_portal/portal_web/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.conf import settings
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView
from django.contrib import messages
from .forms import SignUpForm, SignInForm
from .models import PlayerProfile
from .utils import Puzzle, convert_timestamp_from_json
import requests
import datetime
from datetime import timezone
import redis
import json


redis = redis.Redis(**settings.REDIS)


class StatisticsAPIMixin:
    """Mixing to work with statistics API. Endpoint must be specified"""
    url = 'http://statapp:9000/api/'
    endpoint = None
    pk = None
    parameters = None
    json = None

    def get_attributes(self, endpoint, parameters, json):
        if not endpoint:
            endpoint = self.endpoint
        if not parameters:
            parameters = self.parameters
        if not json:
            json = self.json
        return endpoint, parameters, json

    def get_response(self, endpoint=None, parameters=None, json=None):
        endpoint, parameters, json = self.get_attributes(endpoint, parameters, json)
        if self.pk:
            r = requests.get(self.url + endpoint + str(self.pk), params=parameters, json=json)
        else:
            r = requests.get(self.url + endpoint, params=parameters, json=json)
        try:
            return r.json()
        except Exception as err:
            return f'Oops, something went wrong. GET method. Json cannot be parsed. {err}'

    def post_request(self, endpoint=None, parameters=None, json=None):
        endpoint, parameters, json = self.get_attributes(endpoint, parameters, json)
        if self.pk:
            r = requests.post(self.url + endpoint + str(self.pk)+'/', params=parameters, json=json)
        else:
            r = requests.post(self.url + endpoint, params=parameters, json=json)
        try:
            return r.json()
        except:
            return 'Oops, something went wrong. POST method. Json cannot be parsed'


class IndexView(LoginRequiredMixin, StatisticsAPIMixin, View):
    template = 'portal_web/home.html'
    login_url = reverse_lazy('portal_web:login')

    endpoint = 'player_stats/'

    def build_line_chart_data(self, statistics: list) -> list:
        data = []
        for item in statistics:
            x = item['battles']
            y = item['wn8']
            data.append({'x': x, 'y': y})
        return data

    def build_week_widget_data(self, statistics: list) -> dict:
        one_week = datetime.datetime.now(timezone.utc) - datetime.timedelta(days=7)
        seven_days_data = [item for item in statistics if convert_timestamp_from_json(item.get('created_at')) > one_week]
        if not seven_days_data:
            return {'battles_changed': 0, 'wn8_changed': round(0, 2)}
        reference_point = len(seven_days_data) + 1 if len(statistics) > 1 else 0
        first = statistics[-reference_point]
        latest = statistics[-1]
        battles_changed = latest['battles'] - first['battles']
        wn8_changed = latest['wn8'] - first['wn8']
        return {'battles_changed': battles_changed, 'wn8_changed': round(wn8_changed, 2)}

    def get_statistics(self):
        cache_id_mask = f'stats:{self.pk}'
        cached_statistics = redis.get(cache_id_mask)
        if cached_statistics:
            statistics = json.loads(cached_statistics)
        else:
            statistics = self.get_response()
            redis.set(cache_id_mask, json.dumps(statistics))
            redis.expire(cache_id_mask, 1800)
        return statistics

    def get(self, request, *args, **kwargs):
        player_profile = PlayerProfile.objects.filter(user=request.user).first()
        if not player_profile:
            return render(request, 'portal_web/set_profile.html')
        self.pk = player_profile.player_id
        statistics = self.get_statistics()
        try:
            player_profile.battles, player_profile.current_wn8 = statistics[-1]['battles'], statistics[-1]['wn8']
            player_profile.save()
            line_chart_data = self.build_line_chart_data(statistics)
            widget_data = self.build_week_widget_data(statistics)
            context = {'profile': player_profile, 'line_chart_data': line_chart_data, 'widget_data': widget_data}
            return render(request, self.template, context)
        except TypeError:
            messages.error(request,  statistics)
            return render(request, self.template)
        except KeyError as err:
            messages.error(request, f'Cannot access key {err}')
            return render(request, self.template)


class CustomLoginView(LoginView):
    template_name = 'portal_web/login.html'
    authentication_form = SignInForm
    redirect_authenticated_user = True


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'portal_web/sign_up.html'
    success_url = reverse_lazy('portal_web:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        return super().form_valid(form)


class WGPlayerSearchView(LoginRequiredMixin, StatisticsAPIMixin, View):
    endpoint = 'get_players/'

    def get(self, request, *args, **kwargs):
        username = request.GET.get('username')
        self.parameters = {'username': username}
        players = self.get_response()
        context = {'players': players}
        return render(request, 'portal_web/set_profile.html', context)


class CreateProfileView(LoginRequiredMixin, StatisticsAPIMixin, View):
    endpoint = 'create_player/'
    json = None

    def post(self, request, *args, **kwargs):
        player_id = request.POST.get('player')
        player_nickname = request.POST.get('nickname')
        PlayerProfile.objects.create(user=request.user, player_id=player_id, nickname=player_nickname)
        self.json = {'player_id': player_id}
        stat_response = self.post_request()
        return redirect(reverse_lazy('portal_web:index'))


class DetailedStatView(LoginRequiredMixin, StatisticsAPIMixin, View):
    endpoint = 'detailed_stats/'
    pk = None

    def get(self, request, *args, **kwargs):
        self.pk = request.GET.get('player_id')
        cache_key = 'detailed_stat:' + self.pk
        cached_detailed_stat = redis.get(cache_key)
        if cached_detailed_stat:
            detailed_stat = json.loads(cached_detailed_stat)
        else:
            detailed_stat = self.get_response()
            redis.set(cache_key, json.dumps(detailed_stat))
            redis.expire(cache_key, 300)
        context = {'detailed_stat': detailed_stat}
        return render(request, 'portal_web/detailed_stats.html', context)


class ProfileView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = request.user
        profile = PlayerProfile.objects.filter(user=user).first()
        context = {'profile': profile, 'premium': user.has_perm('portal_web.premium_account')}
        return render(request, 'portal_web/profile.html', context)

    def post(self, request, *args, **kwargs):
        user = request.user
        desired_wn8 = request.POST.get('desired_wn8')
        profile = PlayerProfile.objects.filter(user=user).first()
        profile.desired_wn8 = desired_wn8
        profile.save()
        context = {'profile': profile, 'premium': user.has_perm('portal_web.premium_account')}
        return render(request, 'portal_web/profile.html', context)


class SubscriptionView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        puzzle = Puzzle()
        return render(request, 'portal_web/subscription.html', {'puzzle': puzzle})

    def post(self, request, *args, **kwargs):
        a = int(request.POST.get('a'))
        b = int(request.POST.get('b'))
        result = int(request.POST.get('result'))
        if result == a + b:
            permission = Permission.objects.get(name='User has access to premium features')
            user = request.user
            user.user_permissions.add(permission)
            profile = PlayerProfile.objects.filter(user=user).first()
            profile.premium_expires = datetime.datetime.now() + datetime.timedelta(days=2)
            profile.save()
            messages.success(request, 'Your subscription was successful!')
        else:
            messages.error(request, 'Premium subscription failed')
        return redirect(reverse_lazy('portal_web:profile'))


class BoostView(LoginRequiredMixin, PermissionRequiredMixin, StatisticsAPIMixin, View):
    permission_required = 'portal_web.premium_account'
    endpoint = 'detailed_stats/'

    def get(self, request, *args, **kwargs):
        user_profile = PlayerProfile.objects.filter(user=request.user).first()
        self.pk = user_profile.player_id
        if user_profile.desired_wn8:
            self.parameters = {'rating': user_profile.desired_wn8}
        else:
            self.parameters = {'rating': int(user_profile.current_wn8)}
        boost_tanks = self.get_response()
        boost_tanks_sorted = sorted(boost_tanks, key=lambda t: t['weighted'])
        context = {'boost_tanks': boost_tanks_sorted}
        return render(request, 'portal_web/boost.html', context)


class TankStatsView(LoginRequiredMixin, PermissionRequiredMixin, StatisticsAPIMixin, View):
    permission_required = 'portal_web.premium_account'
    statistics_endpoint = 'tank_stats/'
    tank_details_endpoint = 'tank_details/'
    desired_damage_endpoint = 'desired_damage/'

    def build_line_chart_data(self, statistics: list) -> list:
        data = []
        for item in statistics:
            x = item['tank_battles']
            y = item['tank_wn8']

player_portal/portal_web/templates/portal_web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'portal_web/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
</head>
<body>
<div class="container">
  <ul class="nav bg-info">
    <li class="nav-item">
      <a class="nav-link link-light" href="{% url 'portal_web:index' %}">STATISTICS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="{% url 'portal_web:boost' %}">BOOST RECOMENDATIONS</a>
    </li>
    {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
          <a class="nav-link link-light dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              PROFILE
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'portal_web:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'portal_web:logout' %}">Logout</a></li>
          </ul>
      </li>
    {% endif %}
  </ul>
</div>

  {% block content %}
  {% endblock %}

<div class="container">
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
</div>
</body>
</html>

player_portal/portal_web/templates/portal_web/boost.html
{% extends 'portal_web/base.html' %}

{% block content %}

{% load static %}

<div class="container">
    <h3 class="text-center my-4">Boost recommendations</h3>
    {% if not request.user.playerprofile.desired_wn8 %}
        <div class="card text-center my-3">
            <div class="card-header">
                Hint
            </div>
            <div class="card-body">
                <h5 class="card-title">Receive better recommendations</h5>
                <p class="card-text">Set your desired WN8 in Profile Settings to get better recommendations</p>
                <a href="{% url 'portal_web:profile' %}" class="btn btn-primary">Go to Profile</a>
            </div>
        </div>
    {% endif %}
    {%for tank in boost_tanks %}
        {% if forloop.counter0|divisibleby:"4" %}
        <div class="row">
        {% endif %}
            <div class="col">
                <div class="tank-card card mx-2 my-3" style="width: 18rem;">
                    <div class="card-header">
                        <h5 class="card-title">{{ tank.tank_name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            {% if tank.tank_type == "heavyTank" %}
                                <img src="{% static 'portal_web/icons/heavy_tank_icon.svg' %}" alt="Heavy Tank" class="icon-small">
                            {% elif tank.tank_type == "AT-SPG" %}
                                <img src="{% static 'portal_web/icons/at_spg_icon.svg' %}" alt="AT-SPG Tank" class="icon-small">
                            {% elif tank.tank_type == "mediumTank" %}
                                <img src="{% static 'portal_web/icons/medium_tank_icon.svg' %}" alt="Medium Tank" class="icon-small">
                            {% elif tank.tank_type == "lightTank" %}
                                <img src="{% static 'portal_web/icons/light_tank_icon.svg' %}" alt="Light Tank" class="icon-small">
                            {% elif tank.tank_type == "SPG" %}
                                <img src="{% static 'portal_web/icons/spg_icon.svg' %}" alt="SPG Tank" class="icon-small">
                            {% else %}
                                {{ tank.tank_type }}
                            {% endif %}
                            <span>
                                Tier: {{ tank.tank_tier }}
                            </span>
                        </h6>
                    </div>
                    <img src="{{ tank.big_icon }}" class="card-img-top" alt="...">
                      <div class="card-body">
                          <ul class="list-group list-group-flush">
                              <li class="list-group-item">Battles: {{tank.tank_battles }}</li>
                              <li class="list-group-item">WN8: {{ tank.tank_wn8 }}</li>
                          </ul>
                          <a href="{% url 'portal_web:tank_stats' tank.wg_tank_id %}" class="stretched-link"></a>
                      </div>
                </div>
            </div>
        {% if forloop.counter0|add:"1"|divisibleby:"4" %}
            </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}

player_portal/portal_web/templates/portal_web/detailed_stats.html
{% load static %}

<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Tank</th>
            <th scope="col">Type</th>
            <th scope="col">Tier</th>
            <th scope="col">Nation</th>
            <th scope="col">Battles</th>
            <th scope="col">WN8</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for item in detailed_stat %}
        <tr>
            <th scope="row"><img src="{{ item.contour_icon }}"></th>
            <td>{{ item.tank_name }}</td>
            <td>
                {% if item.tank_type == "heavyTank" %}
                    <img src="{% static 'portal_web/icons/heavy_tank_icon.svg' %}" alt="Heavy Tank" class="icon-small">
                {% elif item.tank_type == "AT-SPG" %}
                    <img src="{% static 'portal_web/icons/at_spg_icon.svg' %}" alt="AT-SPG Tank" class="icon-small">
                {% elif item.tank_type == "mediumTank" %}
                    <img src="{% static 'portal_web/icons/medium_tank_icon.svg' %}" alt="Medium Tank" class="icon-small">
                {% elif item.tank_type == "lightTank" %}
                    <img src="{% static 'portal_web/icons/light_tank_icon.svg' %}" alt="Light Tank" class="icon-small">
                {% elif item.tank_type == "SPG" %}
                    <img src="{% static 'portal_web/icons/spg_icon.svg' %}" alt="SPG Tank" class="icon-small">
                {% else %}
                    {{ item.tank_type }}
                {% endif %}
            </td>
            <td>{{ item.tank_tier }}</td>
            <td>{{ item.tank_nation }}</td>
            <td>{{ item.tank_battles }}</td>
            <td>{{ item.tank_wn8 }}</td>
            <td><a href="{% url 'portal_web:tank_stats' item.wg_tank_id %}">Details</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

player_portal/portal_web/templates/portal_web/home.html
{% extends 'portal_web/base.html' %}

{% load static %}
{% load bootstrap_icons %}

{% block content %}
<body>
<div class="container mt-3">
    <div class="row mb-2">
        <div class="col my-2 d-flex flex-column justify-content-between">
            <div class="card flex-fill">
                <h5 class="card-header">{{ profile.nickname }}</h5>
                <span hidden id="playerID">{{ profile.player_id }}</span>
                <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                Battles:
                            </div>
                            <div class="col text-left">
                                {{ profile.battles }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-2">
                                WN8:
                            </div>
                            <div class="col text-left">
                                {{ profile.current_wn8 }}
                            </div>
                        </div>
                </div>
            </div>
            <div class="card flex-fill mt-2">
                <div class="card-header text-center">
                    7 days summary
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-3">
                            Battles played:
                        </div>
                        <div class="col-2 text-end">
                            {% if widget_data.battles_changed > 0%}+{% endif %}{{ widget_data.battles_changed }}
                        </div>
                        <div class="col">
                            {% if widget_data.battles_changed > 0 %}{% bs_icon 'arrow-up-circle-fill' color='green' %}{% elif widget_data.battles_changed < 0 %}{% bs_icon 'arrow-down-circle-fill' color='red' %}{% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            WN8 changed:
                        </div>
                        <div class="col-2 text-end">
                            {% if widget_data.wn8_changed > 0 %}+{% endif %}{{ widget_data.wn8_changed }}
                        </div>
                        <div class="col">
                            {% if widget_data.wn8_changed > 0 %}{% bs_icon 'arrow-up-circle-fill' color='green' %}{% elif widget_data.wn8_changed < 0 %}{% bs_icon 'arrow-down-circle-fill' color='red' %}{% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6 my-2" id="wn8chart">
            <canvas id="leftChart" class="scatter-chart"></canvas>
        </div>
    </div>
    <div class="accordion" id="accordionTanksStats">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button collapsed" id="accordionButtonCollapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Tanks Statistics
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionTanksStats">
                <div class="accordion-body">
                    <div class="container-fluid" id="statTable"></div>
                </div>
            </div>
        </div>
    </div>

    <div hidden>{{ line_chart_data|json_script:"chart-data" }}</div>


</div>
<script src="{% static 'portal_web/js/home_utils.js' %}"></script>
</body>

{% endblock %}

player_portal/portal_web/templates/portal_web/login.html
{% extends 'portal_web/base.html' %}

{% block content %}
<body>
<article class="card-body mx-auto" style="max-width: 400px;">
    <h4 class="card-title mt-3 text-center">Sign In</h4>
    <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text"> <i class="fa fa-user">U</i> </span>
            </div>
            {{ form.username }}
        </div>
        <div class="input-group mb-3">
    	    <div class="input-group-prepend">
		        <span class="input-group-text"> <i class="fa fa-envelope">P</i> </span>
		    </div>
            {{ form.password }}
        </div>
        <span>{{ form.non_field_errors }}</span>
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary" type="button">Log In</button>
            <a class="btn btn-outline-primary" href="{% url 'portal_web:sign_up' %}" role="button">Create an account</a>
        </div>
    </form>
</article>
</body>
{% endblock %}

player_portal/portal_web/templates/portal_web/logout.html
{% extends 'portal_web/base.html' %}

{% block content %}
    <article class="card-body mx-auto" style="max-width: 400px;">
        <h4 class="card-title mt-3 text-center">Logout successful</h4>
    </article>
{% endblock %}

player_portal/portal_web/templates/portal_web/player_search_results.html
{% load static %}

<body>
<form action="{% url 'portal_web:create_profile' %}"method="post" id="playerForm">
    {% csrf_token %}
    <select class="form-select" size="10" aria-label="player search results" name="player" id="playerSelect">
        {% for player in players %}
            <option value="{{ player.account_id }}" data-nickname="{{ player.nickname }}">{{ player.nickname }}</option>
        {% endfor %}
    </select>
    <input type="hidden" name="nickname" id="playerNickname">
    <div class="d-grid gap-2 my-2">
        <button type="submit" class="btn btn-primary" type="button">Connect Account</button>
    </div>
</form>

    <script src="{% static 'portal_web/js/player_search_results_utils.js' %}"></script>

</body>

player_portal/portal_web/templates/portal_web/profile.html
{% extends 'portal_web/base.html' %}

{% block content %}
<div class="container">
    <form method="post" action="{% url 'portal_web:profile' %}">
        {% csrf_token %}
        <div class="row my-2">
            <label for="staticNickname" class="col-sm-2 col-form-label">Nickname:</label>
            <div class="col-4">
                <input type="text" readonly class="form-control-plaintext" id="staticNickname" value="{{ profile.nickname }}">
            </div>
        </div>
        <div class="row my-2">
            <label for="staticPlayerID" class="col-sm-2 col-form-label">Player ID:</label>
            <div class="col-3">
                <input type="text" readonly class="form-control-plaintext" id="staticPlayerID" value="{{ profile.player_id }}">
            </div>
        </div>
        <div class="row my-2">
            <label for="staticPremium" class="col-sm-2 col-form-label">Premium:</label>
            <div class="col-2">
                <input type="text" readonly class="form-control-plaintext" id="staticPremium" value="{% if premium %}Expires: {{ profile.premium_expires.date }} {% else %}No subscription {% endif %}">
            </div>
            <div class="col">
                <div class="d-grid gap-2 col-2">
                    <a class="btn btn-primary {% if premium%}disabled{% endif %}" href="{% url 'portal_web:subscription' %}" role="button">Upgrade</a>
                </div>
            </div>
        </div>
        <div class="row my-2">
            <label for="staticBattles" class="col-sm-2 col-form-label">Battles:</label>
            <div class="col-3">
                <input type="text" readonly class="form-control-plaintext" id="staticBattles" value="{{ profile.battles }}">
            </div>
        </div>
        <div class="row my-2">
            <label for="staticCurrentWN8" class="col-sm-2 col-form-label">Current WN8:</label>
            <div class="col-3">
                <input type="text" readonly class="form-control-plaintext" id="staticCurrentWN8" value="{{ profile.current_wn8 }}">
            </div>
        </div>
        <div class="row my-2">
            <label for="inputDesiredWN8" class="col-sm-2 col-form-label">Desired WN8:</label>
            <div class="col-2">
                <input name="desired_wn8" type="number" max="9999" class="form-control" id="inputDesiredWN8" value="{{ profile.desired_wn8 }}">
            </div>
            <div class="col">
                <div class="d-grid gap-2 col-2">
                    <button type="submit" class="btn btn-primary mb-3">Save</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

player_portal/portal_web/templates/portal_web/set_profile.html
{% extends 'portal_web/base.html' %}

{% load static %}

{% block content %}
<body>
<article class="card-body mx-auto w-50">
    <h4 class="card-title mt-3 text-center">Link your WoT account</h4>
    <form method="get" action="{% url 'portal_web:wg_player_search' %}" class="row g-3">
        <div class="col-9">
            <input type="text" class="form-control" id="nicknameSearch" name="username" placeholder="WoT Nickname" value="{{ username }}">
        </div>
        <div class="col-3 d-grid gap-2">
            <button type="submit" id="submitButton" class="btn btn-primary mb-3">Search</button>
        </div>
    </form>
    {% if players %}
    {% include 'portal_web/player_search_results.html' %}
    {% endif %}
</article>

<script src="{% static 'portal_web/js/set_profile_utils.js' %}"></script>

</body>
{% endblock %}

player_portal/portal_web/templates/portal_web/subscription.html
{% extends 'portal_web/base.html' %}

{% block content %}
<div class="container my-4">
    <form class="row" method="post" action="{% url 'portal_web:subscription' %}">
        {% csrf_token %}
        <div class="col-1">
            <label for="staticA" class="visually-hidden">a</label>
            <input name="a" type="text" readonly class="form-control-plaintext" id="staticA" value="{{ puzzle.a }}">
        </div>
        <div class="col-1">
            <span>+</span>
        </div>
        <div class="col-1">
            <label for="staticB" class="visually-hidden">a</label>
            <input name="b" type="text" readonly class="form-control-plaintext" id="staticB" value="{{ puzzle.b }}">
        </div>
        <div class="col-1">
            <span>=</span>
        </div>
        <div class="col-1">
            <label for="inputResult" class="visually-hidden">Password</label>
            <input name="result" type="number" class="form-control" id="inputResult" placeholder="Result">
        </div>
        <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Submit answer</button>
      </div>
    </form>
</div>


{% endblock %}